import { Borrower } from "./Borrower";
import { Business } from "./Business";
import { CoBorrower } from "./CoBorrower";
import { Credit } from "./Credit";
import { Employer } from "./Employer";
import { Funding } from "./Funding";
import { Investor } from "./Investor";
import { IssuingBankId } from "./IssuingBankId";
import { Merchant } from "./Merchant";
import { OFAC } from "./OFAC";
import { Sell } from "./Sell";
import { Servicer } from "./Servicer";
import { Submitter } from "./Submitter";
import { TILA } from "./TILA";

export interface ApprovePreApprovalLoanRequest {
    applicationId: string;
    issuingBankId: IssuingBankId;
    platform: string;
    applicationDate: Date;
    program: string;
    borrowers: Array<Borrower>;
    coBorrowers?: Array<CoBorrower> | null;
    employers?: Array<Employer> | null;
    merchant?: Merchant;
    business?: Business;
    submitter: Submitter;
    funding?: Funding;
    investor?: Investor;
    loanNumber: string;
    noteDate: Date;
    approvedLoanAmount?: number;
    loanAmount?: number;
    servicer: Servicer;
    tila: TILA;
    creditObject: Credit;
    loanPurpose: string;
    ofac: OFAC;
    sell: Sell;
}
